code --install-extension EditorConfig.EditorConfig
code --install-extension anseki.vscode-color
code --install-extension eg2.tslint
code --install-extension mohsen1.prettify-json
code --install-extension ms-vscode.sublime-keybindings
code --install-extension pmneo.tsimporter
code --install-extension ryu1kn.annotator
code --install-extension sbrink.elm
code --install-extension waderyan.gitblame
